version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    container_name: db
    restart: always
    expose:
      - "5432"
    volumes:
      - data_volume:/var/lib/postgresql/data/
    env_file:
      - ../environments/postgres.env
      - ${PG_LOCAL_ENV_FILE:-environments/noop.env}
    user: ${POSTGRES_USER:-postgres}
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 20

  auth_service:
    build:
      context: ../auth_service
    container_name: auth_service
    restart: always
    env_file:
      - ../environments/redis.env
      - ../environments/auth_service.env
      - ../environments/db.env
      - ${FAST_API_LOCAL_ENV_FILE:-environments/noop.env}
    expose:
      - "8080"
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  data_volume:
  redis_data: